print("Hello World")
print("my bitchass is writing to a file")
print("my bitchass is writing to a file")
print("my bitchass is writing to a file")
print("my bitchass is writing to a file")
print("my bitchass is writing a file")
print("my bitchass is writing a file")